insert into hats values(0,'bucket','felt','black','./images/Bucket.png','Bulgarians refer to bucket hats as "idiotka", which means idiot hats'),
(0,'bucket','felt','red','./images/Bucket.png','Bulgarians refer to bucket hats as "idiotka", which means idiot hats'),
(0,'bucket','felt','blue','./images/Bucket.png','Bulgarians refer to bucket hats as "idiotka", which means idiot hats'),
(0,'bucket','felt','forest-green','./images/Bucket.png','Bulgarians refer to bucket hats as "idiotka", which means idiot hats'),
(0,'fedora','felt','black','./images/Fedora.png','Before Prince Edward of Wales kickstarted the fedora’s popularity among men, the fedora was originally a woman’s hat. '),
(0,'fedora','felt','black','./images/Fedora.png','Before Prince Edward of Wales kickstarted the fedora’s popularity among men, the fedora was originally a woman’s hat. '),
(0,'fedora','felt','tartan','./images/Fedora.png','Before Prince Edward of Wales kickstarted the fedora’s popularity among men, the fedora was originally a woman’s hat. '),
(0,'fedora','straw','straw','./images/Fedora.png','Before Prince Edward of Wales kickstarted the fedora’s popularity among men, the fedora was originally a woman’s hat. '),
(0,'bowler','felt','black','./images/Bowler.png','The purpose of the design was to protect gamekeepers from hitting their heads on low hanging branches while riding on horses. '),
(0,'bowler','felt','black','./images/Bowler.png','The purpose of the design was to protect gamekeepers from hitting their heads on low hanging branches while riding on horses. '),
(0,'bowler','felt','green','./images/Bowler.png','The purpose of the design was to protect gamekeepers from hitting their heads on low hanging branches while riding on horses. '),
(0,'bowler','felt','purple','./images/Bowler.png','The purpose of the design was to protect gamekeepers from hitting their heads on low hanging branches while riding on horses. '),
(0,'bowler','felt','maroon5','./images/Bowler.png','The purpose of the design was to protect gamekeepers from hitting their heads on low hanging branches while riding on horses. '),
(0,'beanie','cotton','black','./images/Beanie.png','In Fargo, North Dakota, people aren’t allowed to wear beanies, or hats of any kind, while dancing'),
(0,'beanie','cotton','red plaid','./images/Beanie.png','In Fargo, North Dakota, people aren’t allowed to wear beanies, or hats of any kind, while dancing'),
(0,'beanie','cotton','red white stripes','./images/Beanie.png','In Fargo, North Dakota, people aren’t allowed to wear beanies, or hats of any kind, while dancing'),
(0,'beanie','cotton','blue','./images/Beanie.png','In Fargo, North Dakota, people aren’t allowed to wear beanies, or hats of any kind, while dancing'),
(0,'beanie','cotton','yellow','./images/Beanie.png','In Fargo, North Dakota, people aren’t allowed to wear beanies, or hats of any kind, while dancing'),
(0,'top','felt','black','./images/TopHat.png','Historians suggest that a top hat saved America’s 16th President, Abraham Lincoln, from an assassination attempt earlier in his career.'),
(0,'top','felt','white','./images/TopHat.png','Historians suggest that a top hat saved America’s 16th President, Abraham Lincoln, from an assassination attempt earlier in his career.'),
(0,'top','felt','yellow','./images/TopHat.png','Historians suggest that a top hat saved America’s 16th President, Abraham Lincoln, from an assassination attempt earlier in his career.'),
(0,'top','felt','orange','./images/TopHat.png','Historians suggest that a top hat saved America’s 16th President, Abraham Lincoln, from an assassination attempt earlier in his career.'),
(0,'top','felt','lime','./images/TopHat.png','Historians suggest that a top hat saved America’s 16th President, Abraham Lincoln, from an assassination attempt earlier in his career.'),
(0,'trucker','vynil/polyester','red','./images/Trucker.png','Originally, the trucker hat was a mere token given away by companies to farmers, rural workers, and truckers in the United States.'),
(0,'trucker','vynil/polyester','white','./images/Trucker.png','Originally, the trucker hat was a mere token given away by companies to farmers, rural workers, and truckers in the United States.'),
(0,'trucker','vynil/polyester','blue','./images/Trucker.png','Originally, the trucker hat was a mere token given away by companies to farmers, rural workers, and truckers in the United States.'),
(0,'trucker','vynil/polyester','black','./images/Trucker.png','Originally, the trucker hat was a mere token given away by companies to farmers, rural workers, and truckers in the United States.'),
(0,'trucker','vynil/polyester','red','./images/Trucker.png','Originally, the trucker hat was a mere token given away by companies to farmers, rural workers, and truckers in the United States.'),
(0,'panama','straw','straw','./images/Panama.png','A Panama Hat is a reference to the straw material it is made from, not the country of Panama.'),
(0,'panama','straw','white straw','./images/Panama.png','A Panama Hat is a reference to the straw material it is made from, not the country of Panama.'),
(0,'beret','felt','black','./images/Beret.png','The Beret has it’s own Museum in Navy, Fance '),
(0,'beret','felt','red','./images/Beret.png','The Beret has it’s own Museum in Navy, Fance '),
(0,'beret','felt','blue','./images/Beret.png','The Beret has it’s own Museum in Navy, Fance '),
(0,'beret','felt','forest green','./images/Beret.png','The Beret has it’s own Museum in Navy, Fance '),
(0,'beret','felt','burgundy','./images/Beret.png','The Beret has it’s own Museum in Navy, Fance '),
(0,'baseball cap','cotton','black','./images/Baseball.png','The first team to wear a baseball cap Brooklyn Excelsiors in 1860'),
(0,'baseball cap','cotton','black','./images/Baseball.png','The first team to wear a baseball cap Brooklyn Excelsiors in 1860'),
(0,'baseball cap','cotton','black','./images/Baseball.png','The first team to wear a baseball cap Brooklyn Excelsiors in 1860'),
(0,'baseball cap','cotton','black','./images/Baseball.png','The first team to wear a baseball cap Brooklyn Excelsiors in 1860'),
(0,'baseball cap','cotton','black','./images/Baseball.png','The first team to wear a baseball cap Brooklyn Excelsiors in 1860'),
(0,'straw','straw','straw','./images/Straw.png','One straw hat is particularly famous, having been worn by Gol D. Roger and Shanks. It is now worn by Monkey D. Luffy, giving him his epithet "Straw Hat Luffy".'),
(0,'homburg','felt','black','./images/Homburg.png','The homburg became popular in Europe after England\'s King Edward VII visited Germany and returned with a hat of this style '),
(0,'homburg','felt','gray','./images/Homburg.png','The homburg became popular in Europe after England\'s King Edward VII visited Germany and returned with a hat of this style '),
(0,'homburg','felt','blue','./images/Homburg.png','The homburg became popular in Europe after England\'s King Edward VII visited Germany and returned with a hat of this style '),
(0,'homburg','felt','maroon','./images/Homburg.png','The homburg became popular in Europe after England\'s King Edward VII visited Germany and returned with a hat of this style '),
(0,'homburg','felt','sepia','./images/Homburg.png','The homburg became popular in Europe after England\'s King Edward VII visited Germany and returned with a hat of this style ');


insert into users values(0,"Hemory","Phifer"),
(0,"Calyn","Greene"),
(0,"Marjorie","Patton"),
(0,"Ramone","Lynch"),
(0,"James","Mitchell");

insert into myhats values(0,1,12),(0,1,2),(0,1,25),(0,2,22),(0,2,37),(0,3,26),(0,3,27),(0,3,23),(0,4,24);

insert into monthlyhats values(0,1,12,'02-01-2022'),(0,2,22,'02-02-2022');